apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zentao
  name: zentao
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zentao
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: zentao
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          image: easysoft/zentao:18.1
          name: env-7
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /www/zentaopms
              name: zentao-claim0
            - mountPath: /var/lib/mysql
              name: zentao-claim1
      restartPolicy: Always
      volumes:
        - name: zentao-claim0
          persistentVolumeClaim:
            claimName: zentao-claim0
        - name: zentao-claim1
          persistentVolumeClaim:
            claimName: zentao-claim1
