services:
    zentao:
        container_name: env-7
        ports:
            - 1234:80
        volumes:
            - /www/zentaopms:/www/zentaopms
            - /www/mysqldata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            # Admin123456
        image: easysoft/zentao:18.1
